# -*- coding: utf-8 -*-
"""
V2.1 i18n 补齐：为 9 份字典新增 admin 命名空间 + membership 的 2 个结账状态键。

铁律（本项目踩过的坑）：
  - io.open 读写两端都要 newline=""，否则 CRLF 被 Python 转成 LF，整文件 diff 爆炸
  - 写回时把 \n 统一替换成 \r\n
  - 改完核对 raw.count(b"\r\n") 不变（基线 3238 + 新增行数）
"""
import io
import json
import os
import shutil

ROOT = os.path.dirname(os.path.dirname(os.path.abspath(__file__)))
DICT_DIR = os.path.join(ROOT, "i18n", "dictionaries")
BACKUP_DIR = os.path.join(ROOT, ".workbuddy", "dict-backup-before-v21-admin")

LOCALES = ["en", "zh", "zh-TW", "es", "de", "fr", "pt", "ja", "ar"]

# ---------------------------------------------------------------------------
# admin 命名空间（9 语）
# key 顺序与英文基准一致，缺失时自动用英文兜底
# ---------------------------------------------------------------------------

EN = {
    "title": "Admin",
    "backToSite": "Back to site",
    "navLabel": "Admin navigation",
    "navOverview": "Overview",
    "navSuppliers": "Suppliers",
    "navRfqs": "RFQs",
    "navMembers": "Members",
    "overviewTitle": "Overview",
    "overviewLead": "Platform activity at a glance.",
    "statUsers": "Users",
    "statPaid": "Paid members",
    "statSuppliers": "Suppliers",
    "statNewRfqs": "New RFQs (7 days)",
    "statTotalRfqs": "Total RFQs",
    "recentRfqs": "Recent RFQs",
    "viewAll": "View all",
    "suppliersTitle": "Suppliers",
    "suppliersLead": "Edit supplier records and set which tier can see each profile.",
    "suppliersEmpty": "No suppliers yet",
    "suppliersEmptyHint": "Run the seed script to import suppliers, or add one here.",
    "colName": "Name",
    "colCountry": "Country",
    "colRisk": "Risk score",
    "colTier": "Access tier",
    "colPublished": "Published",
    "colReference": "Reference",
    "colProduct": "Product",
    "colEmail": "Email",
    "colStatus": "Status",
    "colCreated": "Submitted",
    "colPlan": "Plan",
    "colPeriodEnd": "Period ends",
    "edit": "Edit",
    "backToList": "Back to list",
    "save": "Save changes",
    "saving": "Saving...",
    "saved": "Saved",
    "error": "Something went wrong. Please try again.",
    "fieldLegalName": "Legal name",
    "fieldCity": "City",
    "fieldIndustry": "Industry",
    "fieldBusinessType": "Business type",
    "fieldEstablished": "Established",
    "fieldEmployees": "Employees",
    "fieldVerification": "Verification status",
    "fieldRiskScore": "Risk score",
    "fieldAuditStatus": "Audit status",
    "fieldInspectionHistory": "Inspection history",
    "fieldAccessTier": "Access tier",
    "fieldPublished": "Published",
    "tier": "Tier",
    "tierHint": "public = visible to everyone. free = signed-in users. paid = Founding Buyer only.",
    "riskHint": "Higher score means lower risk. Range 0 to 100.",
    "status": "Status",
    "yes": "Yes",
    "no": "No",
    "rfqsTitle": "RFQs",
    "rfqsLead": "Buyer inquiries and their status.",
    "rfqsEmpty": "No RFQs yet",
    "statusNew": "New",
    "statusReviewing": "Reviewing",
    "statusMatched": "Matched",
    "statusClosed": "Closed",
    "membersTitle": "Members",
    "membersLead": "Accounts and their membership status.",
    "membersEmpty": "No members yet",
    "planFree": "Free",
    "planFounding": "Founding Buyer",
    "statusActive": "Active",
    "statusCanceled": "Canceled",
    "statusPastDue": "Past due",
    "statusExpired": "Expired",
    "notConfigured": "No data: the database is not configured yet.",
    "noData": "No data",
}

ZH = {
    "title": "管理后台",
    "backToSite": "返回前台",
    "navLabel": "后台导航",
    "navOverview": "概览",
    "navSuppliers": "供应商",
    "navRfqs": "询价单",
    "navMembers": "会员",
    "overviewTitle": "概览",
    "overviewLead": "平台动态一览。",
    "statUsers": "用户数",
    "statPaid": "付费会员",
    "statSuppliers": "供应商",
    "statNewRfqs": "新询价（7 天）",
    "statTotalRfqs": "询价总数",
    "recentRfqs": "最近询价",
    "viewAll": "查看全部",
    "suppliersTitle": "供应商",
    "suppliersLead": "编辑供应商档案，并设定每家档案的可见层级。",
    "suppliersEmpty": "暂无供应商",
    "suppliersEmptyHint": "运行 seed 脚本导入供应商，或在此手动新增。",
    "colName": "名称",
    "colCountry": "国家",
    "colRisk": "风险分",
    "colTier": "可见层级",
    "colPublished": "已发布",
    "colReference": "编号",
    "colProduct": "产品",
    "colEmail": "邮箱",
    "colStatus": "状态",
    "colCreated": "提交时间",
    "colPlan": "套餐",
    "colPeriodEnd": "本周期结束",
    "edit": "编辑",
    "backToList": "返回列表",
    "save": "保存修改",
    "saving": "保存中…",
    "saved": "已保存",
    "error": "出错了，请重试。",
    "fieldLegalName": "公司法定名称",
    "fieldCity": "城市",
    "fieldIndustry": "行业",
    "fieldBusinessType": "企业类型",
    "fieldEstablished": "成立年份",
    "fieldEmployees": "员工规模",
    "fieldVerification": "核验状态",
    "fieldRiskScore": "风险分",
    "fieldAuditStatus": "审核状态",
    "fieldInspectionHistory": "验货次数",
    "fieldAccessTier": "可见层级",
    "fieldPublished": "已发布",
    "tier": "层级",
    "tierHint": "public = 所有人可见；free = 登录后可见；paid = 仅 Founding Buyer 可见。",
    "riskHint": "分数越高表示风险越低，范围 0–100。",
    "status": "状态",
    "yes": "是",
    "no": "否",
    "rfqsTitle": "询价单",
    "rfqsLead": "买家询价及其处理状态。",
    "rfqsEmpty": "暂无询价单",
    "statusNew": "新提交",
    "statusReviewing": "处理中",
    "statusMatched": "已匹配",
    "statusClosed": "已关闭",
    "membersTitle": "会员",
    "membersLead": "账号及其会员状态。",
    "membersEmpty": "暂无会员",
    "planFree": "免费",
    "planFounding": "Founding Buyer",
    "statusActive": "生效中",
    "statusCanceled": "已取消",
    "statusPastDue": "扣款失败",
    "statusExpired": "已过期",
    "notConfigured": "暂无数据：数据库尚未配置。",
    "noData": "无数据",
}

ZH_TW = {
    "title": "管理後台",
    "backToSite": "返回前台",
    "navLabel": "後台導覽",
    "navOverview": "概覽",
    "navSuppliers": "供應商",
    "navRfqs": "詢價單",
    "navMembers": "會員",
    "overviewTitle": "概覽",
    "overviewLead": "平台動態一覽。",
    "statUsers": "用戶數",
    "statPaid": "付費會員",
    "statSuppliers": "供應商",
    "statNewRfqs": "新詢價（7 天）",
    "statTotalRfqs": "詢價總數",
    "recentRfqs": "最近詢價",
    "viewAll": "檢視全部",
    "suppliersTitle": "供應商",
    "suppliersLead": "編輯供應商檔案，並設定每家檔案的可見層級。",
    "suppliersEmpty": "暫無供應商",
    "suppliersEmptyHint": "執行 seed 腳本匯入供應商，或在此手動新增。",
    "colName": "名稱",
    "colCountry": "國家",
    "colRisk": "風險分",
    "colTier": "可見層級",
    "colPublished": "已發布",
    "colReference": "編號",
    "colProduct": "產品",
    "colEmail": "電子郵件",
    "colStatus": "狀態",
    "colCreated": "提交時間",
    "colPlan": "方案",
    "colPeriodEnd": "本週期結束",
    "edit": "編輯",
    "backToList": "返回清單",
    "save": "儲存變更",
    "saving": "儲存中…",
    "saved": "已儲存",
    "error": "發生錯誤，請再試一次。",
    "fieldLegalName": "公司法定名稱",
    "fieldCity": "城市",
    "fieldIndustry": "產業",
    "fieldBusinessType": "企業類型",
    "fieldEstablished": "成立年份",
    "fieldEmployees": "員工規模",
    "fieldVerification": "核驗狀態",
    "fieldRiskScore": "風險分",
    "fieldAuditStatus": "審核狀態",
    "fieldInspectionHistory": "驗貨次數",
    "fieldAccessTier": "可見層級",
    "fieldPublished": "已發布",
    "tier": "層級",
    "tierHint": "public = 所有人可見；free = 登入後可見；paid = 僅 Founding Buyer 可見。",
    "riskHint": "分數越高表示風險越低，範圍 0–100。",
    "status": "狀態",
    "yes": "是",
    "no": "否",
    "rfqsTitle": "詢價單",
    "rfqsLead": "買家詢價及其處理狀態。",
    "rfqsEmpty": "暫無詢價單",
    "statusNew": "新提交",
    "statusReviewing": "處理中",
    "statusMatched": "已配對",
    "statusClosed": "已關閉",
    "membersTitle": "會員",
    "membersLead": "帳號及其會員狀態。",
    "membersEmpty": "暫無會員",
    "planFree": "免費",
    "planFounding": "Founding Buyer",
    "statusActive": "生效中",
    "statusCanceled": "已取消",
    "statusPastDue": "扣款失敗",
    "statusExpired": "已過期",
    "notConfigured": "暫無資料：資料庫尚未設定。",
    "noData": "無資料",
}

ES = {
    "title": "Administración",
    "backToSite": "Volver al sitio",
    "navLabel": "Navegación de administración",
    "navOverview": "Resumen",
    "navSuppliers": "Proveedores",
    "navRfqs": "Solicitudes",
    "navMembers": "Miembros",
    "overviewTitle": "Resumen",
    "overviewLead": "Actividad de la plataforma de un vistazo.",
    "statUsers": "Usuarios",
    "statPaid": "Miembros de pago",
    "statSuppliers": "Proveedores",
    "statNewRfqs": "Solicitudes nuevas (7 días)",
    "statTotalRfqs": "Solicitudes totales",
    "recentRfqs": "Solicitudes recientes",
    "viewAll": "Ver todo",
    "suppliersTitle": "Proveedores",
    "suppliersLead": "Edite los registros y defina qué nivel puede ver cada perfil.",
    "suppliersEmpty": "Aún no hay proveedores",
    "suppliersEmptyHint": "Ejecute el script de carga inicial o añada uno aquí.",
    "colName": "Nombre",
    "colCountry": "País",
    "colRisk": "Puntuación de riesgo",
    "colTier": "Nivel de acceso",
    "colPublished": "Publicado",
    "colReference": "Referencia",
    "colProduct": "Producto",
    "colEmail": "Correo",
    "colStatus": "Estado",
    "colCreated": "Enviado",
    "colPlan": "Plan",
    "colPeriodEnd": "Fin del periodo",
    "edit": "Editar",
    "backToList": "Volver a la lista",
    "save": "Guardar cambios",
    "saving": "Guardando...",
    "saved": "Guardado",
    "error": "Algo salió mal. Inténtelo de nuevo.",
    "fieldLegalName": "Razón social",
    "fieldCity": "Ciudad",
    "fieldIndustry": "Sector",
    "fieldBusinessType": "Tipo de empresa",
    "fieldEstablished": "Fundada en",
    "fieldEmployees": "Empleados",
    "fieldVerification": "Estado de verificación",
    "fieldRiskScore": "Puntuación de riesgo",
    "fieldAuditStatus": "Estado de auditoría",
    "fieldInspectionHistory": "Historial de inspecciones",
    "fieldAccessTier": "Nivel de acceso",
    "fieldPublished": "Publicado",
    "tier": "Nivel",
    "tierHint": "public = visible para todos. free = usuarios registrados. paid = solo Founding Buyer.",
    "riskHint": "Una puntuación más alta indica menor riesgo. Rango de 0 a 100.",
    "status": "Estado",
    "yes": "Sí",
    "no": "No",
    "rfqsTitle": "Solicitudes",
    "rfqsLead": "Consultas de compradores y su estado.",
    "rfqsEmpty": "Aún no hay solicitudes",
    "statusNew": "Nueva",
    "statusReviewing": "En revisión",
    "statusMatched": "Emparejada",
    "statusClosed": "Cerrada",
    "membersTitle": "Miembros",
    "membersLead": "Cuentas y su estado de membresía.",
    "membersEmpty": "Aún no hay miembros",
    "planFree": "Gratis",
    "planFounding": "Founding Buyer",
    "statusActive": "Activa",
    "statusCanceled": "Cancelada",
    "statusPastDue": "Pago pendiente",
    "statusExpired": "Caducada",
    "notConfigured": "Sin datos: la base de datos aún no está configurada.",
    "noData": "Sin datos",
}

DE = {
    "title": "Verwaltung",
    "backToSite": "Zurück zur Website",
    "navLabel": "Verwaltungsnavigation",
    "navOverview": "Übersicht",
    "navSuppliers": "Lieferanten",
    "navRfqs": "Anfragen",
    "navMembers": "Mitglieder",
    "overviewTitle": "Übersicht",
    "overviewLead": "Plattformaktivität auf einen Blick.",
    "statUsers": "Nutzer",
    "statPaid": "Zahlende Mitglieder",
    "statSuppliers": "Lieferanten",
    "statNewRfqs": "Neue Anfragen (7 Tage)",
    "statTotalRfqs": "Anfragen insgesamt",
    "recentRfqs": "Letzte Anfragen",
    "viewAll": "Alle ansehen",
    "suppliersTitle": "Lieferanten",
    "suppliersLead": "Datensätze bearbeiten und Sichtbarkeit je Profil festlegen.",
    "suppliersEmpty": "Noch keine Lieferanten",
    "suppliersEmptyHint": "Führen Sie das Seed-Skript aus oder fügen Sie hier einen hinzu.",
    "colName": "Name",
    "colCountry": "Land",
    "colRisk": "Risikowert",
    "colTier": "Zugriffsstufe",
    "colPublished": "Veröffentlicht",
    "colReference": "Referenz",
    "colProduct": "Produkt",
    "colEmail": "E-Mail",
    "colStatus": "Status",
    "colCreated": "Eingereicht",
    "colPlan": "Tarif",
    "colPeriodEnd": "Zeitraum endet",
    "edit": "Bearbeiten",
    "backToList": "Zurück zur Liste",
    "save": "Änderungen speichern",
    "saving": "Speichern...",
    "saved": "Gespeichert",
    "error": "Etwas ist schiefgelaufen. Bitte erneut versuchen.",
    "fieldLegalName": "Firmenname",
    "fieldCity": "Stadt",
    "fieldIndustry": "Branche",
    "fieldBusinessType": "Unternehmenstyp",
    "fieldEstablished": "Gegründet",
    "fieldEmployees": "Mitarbeiter",
    "fieldVerification": "Verifizierungsstatus",
    "fieldRiskScore": "Risikowert",
    "fieldAuditStatus": "Auditstatus",
    "fieldInspectionHistory": "Inspektionsverlauf",
    "fieldAccessTier": "Zugriffsstufe",
    "fieldPublished": "Veröffentlicht",
    "tier": "Stufe",
    "tierHint": "public = für alle sichtbar. free = angemeldete Nutzer. paid = nur Founding Buyer.",
    "riskHint": "Ein höherer Wert bedeutet geringeres Risiko. Bereich 0 bis 100.",
    "status": "Status",
    "yes": "Ja",
    "no": "Nein",
    "rfqsTitle": "Anfragen",
    "rfqsLead": "Käuferanfragen und ihr Status.",
    "rfqsEmpty": "Noch keine Anfragen",
    "statusNew": "Neu",
    "statusReviewing": "In Prüfung",
    "statusMatched": "Zugeordnet",
    "statusClosed": "Geschlossen",
    "membersTitle": "Mitglieder",
    "membersLead": "Konten und ihr Mitgliedsstatus.",
    "membersEmpty": "Noch keine Mitglieder",
    "planFree": "Kostenlos",
    "planFounding": "Founding Buyer",
    "statusActive": "Aktiv",
    "statusCanceled": "Gekündigt",
    "statusPastDue": "Überfällig",
    "statusExpired": "Abgelaufen",
    "notConfigured": "Keine Daten: Die Datenbank ist noch nicht konfiguriert.",
    "noData": "Keine Daten",
}

FR = {
    "title": "Administration",
    "backToSite": "Retour au site",
    "navLabel": "Navigation d'administration",
    "navOverview": "Vue d'ensemble",
    "navSuppliers": "Fournisseurs",
    "navRfqs": "Demandes",
    "navMembers": "Membres",
    "overviewTitle": "Vue d'ensemble",
    "overviewLead": "L'activité de la plateforme en un coup d'œil.",
    "statUsers": "Utilisateurs",
    "statPaid": "Membres payants",
    "statSuppliers": "Fournisseurs",
    "statNewRfqs": "Nouvelles demandes (7 jours)",
    "statTotalRfqs": "Total des demandes",
    "recentRfqs": "Demandes récentes",
    "viewAll": "Voir tout",
    "suppliersTitle": "Fournisseurs",
    "suppliersLead": "Modifiez les fiches et définissez qui peut voir chaque profil.",
    "suppliersEmpty": "Aucun fournisseur pour l'instant",
    "suppliersEmptyHint": "Lancez le script d'import ou ajoutez-en un ici.",
    "colName": "Nom",
    "colCountry": "Pays",
    "colRisk": "Score de risque",
    "colTier": "Niveau d'accès",
    "colPublished": "Publié",
    "colReference": "Référence",
    "colProduct": "Produit",
    "colEmail": "E-mail",
    "colStatus": "Statut",
    "colCreated": "Envoyé",
    "colPlan": "Formule",
    "colPeriodEnd": "Fin de période",
    "edit": "Modifier",
    "backToList": "Retour à la liste",
    "save": "Enregistrer",
    "saving": "Enregistrement...",
    "saved": "Enregistré",
    "error": "Une erreur est survenue. Veuillez réessayer.",
    "fieldLegalName": "Raison sociale",
    "fieldCity": "Ville",
    "fieldIndustry": "Secteur",
    "fieldBusinessType": "Type d'entreprise",
    "fieldEstablished": "Créée en",
    "fieldEmployees": "Employés",
    "fieldVerification": "Statut de vérification",
    "fieldRiskScore": "Score de risque",
    "fieldAuditStatus": "Statut d'audit",
    "fieldInspectionHistory": "Historique d'inspection",
    "fieldAccessTier": "Niveau d'accès",
    "fieldPublished": "Publié",
    "tier": "Niveau",
    "tierHint": "public = visible par tous. free = utilisateurs connectés. paid = Founding Buyer uniquement.",
    "riskHint": "Un score plus élevé signifie un risque plus faible. Plage de 0 à 100.",
    "status": "Statut",
    "yes": "Oui",
    "no": "Non",
    "rfqsTitle": "Demandes",
    "rfqsLead": "Demandes des acheteurs et leur statut.",
    "rfqsEmpty": "Aucune demande pour l'instant",
    "statusNew": "Nouvelle",
    "statusReviewing": "En cours d'examen",
    "statusMatched": "Rapprochée",
    "statusClosed": "Clôturée",
    "membersTitle": "Membres",
    "membersLead": "Comptes et statut d'adhésion.",
    "membersEmpty": "Aucun membre pour l'instant",
    "planFree": "Gratuit",
    "planFounding": "Founding Buyer",
    "statusActive": "Active",
    "statusCanceled": "Annulée",
    "statusPastDue": "Impayé",
    "statusExpired": "Expirée",
    "notConfigured": "Aucune donnée : la base de données n'est pas encore configurée.",
    "noData": "Aucune donnée",
}

PT = {
    "title": "Administração",
    "backToSite": "Voltar ao site",
    "navLabel": "Navegação administrativa",
    "navOverview": "Visão geral",
    "navSuppliers": "Fornecedores",
    "navRfqs": "Cotações",
    "navMembers": "Membros",
    "overviewTitle": "Visão geral",
    "overviewLead": "Atividade da plataforma em resumo.",
    "statUsers": "Usuários",
    "statPaid": "Membros pagos",
    "statSuppliers": "Fornecedores",
    "statNewRfqs": "Novas cotações (7 dias)",
    "statTotalRfqs": "Total de cotações",
    "recentRfqs": "Cotações recentes",
    "viewAll": "Ver tudo",
    "suppliersTitle": "Fornecedores",
    "suppliersLead": "Edite os registros e defina qual nível pode ver cada perfil.",
    "suppliersEmpty": "Ainda não há fornecedores",
    "suppliersEmptyHint": "Execute o script de importação ou adicione um aqui.",
    "colName": "Nome",
    "colCountry": "País",
    "colRisk": "Pontuação de risco",
    "colTier": "Nível de acesso",
    "colPublished": "Publicado",
    "colReference": "Referência",
    "colProduct": "Produto",
    "colEmail": "E-mail",
    "colStatus": "Status",
    "colCreated": "Enviado",
    "colPlan": "Plano",
    "colPeriodEnd": "Fim do período",
    "edit": "Editar",
    "backToList": "Voltar à lista",
    "save": "Salvar alterações",
    "saving": "Salvando...",
    "saved": "Salvo",
    "error": "Algo deu errado. Tente novamente.",
    "fieldLegalName": "Razão social",
    "fieldCity": "Cidade",
    "fieldIndustry": "Setor",
    "fieldBusinessType": "Tipo de empresa",
    "fieldEstablished": "Fundada em",
    "fieldEmployees": "Funcionários",
    "fieldVerification": "Status de verificação",
    "fieldRiskScore": "Pontuação de risco",
    "fieldAuditStatus": "Status de auditoria",
    "fieldInspectionHistory": "Histórico de inspeção",
    "fieldAccessTier": "Nível de acesso",
    "fieldPublished": "Publicado",
    "tier": "Nível",
    "tierHint": "public = visível para todos. free = usuários logados. paid = somente Founding Buyer.",
    "riskHint": "Quanto maior a pontuação, menor o risco. Intervalo de 0 a 100.",
    "status": "Status",
    "yes": "Sim",
    "no": "Não",
    "rfqsTitle": "Cotações",
    "rfqsLead": "Consultas de compradores e seu status.",
    "rfqsEmpty": "Ainda não há cotações",
    "statusNew": "Nova",
    "statusReviewing": "Em análise",
    "statusMatched": "Correspondida",
    "statusClosed": "Encerrada",
    "membersTitle": "Membros",
    "membersLead": "Contas e seu status de assinatura.",
    "membersEmpty": "Ainda não há membros",
    "planFree": "Gratuito",
    "planFounding": "Founding Buyer",
    "statusActive": "Ativa",
    "statusCanceled": "Cancelada",
    "statusPastDue": "Pagamento em atraso",
    "statusExpired": "Expirada",
    "notConfigured": "Sem dados: o banco de dados ainda não está configurado.",
    "noData": "Sem dados",
}

JA = {
    "title": "管理画面",
    "backToSite": "サイトへ戻る",
    "navLabel": "管理ナビゲーション",
    "navOverview": "概要",
    "navSuppliers": "サプライヤー",
    "navRfqs": "見積依頼",
    "navMembers": "メンバー",
    "overviewTitle": "概要",
    "overviewLead": "プラットフォームの状況をひと目で確認できます。",
    "statUsers": "ユーザー数",
    "statPaid": "有料メンバー",
    "statSuppliers": "サプライヤー",
    "statNewRfqs": "新規見積依頼（7 日間）",
    "statTotalRfqs": "見積依頼総数",
    "recentRfqs": "最近の見積依頼",
    "viewAll": "すべて表示",
    "suppliersTitle": "サプライヤー",
    "suppliersLead": "サプライヤー情報を編集し、閲覧できる層を設定します。",
    "suppliersEmpty": "サプライヤーはまだありません",
    "suppliersEmptyHint": "seed スクリプトを実行して取り込むか、ここから追加してください。",
    "colName": "名称",
    "colCountry": "国",
    "colRisk": "リスクスコア",
    "colTier": "公開レベル",
    "colPublished": "公開",
    "colReference": "参照番号",
    "colProduct": "製品",
    "colEmail": "メール",
    "colStatus": "ステータス",
    "colCreated": "送信日",
    "colPlan": "プラン",
    "colPeriodEnd": "期間終了日",
    "edit": "編集",
    "backToList": "一覧へ戻る",
    "save": "変更を保存",
    "saving": "保存中...",
    "saved": "保存しました",
    "error": "エラーが発生しました。もう一度お試しください。",
    "fieldLegalName": "正式名称",
    "fieldCity": "都市",
    "fieldIndustry": "業種",
    "fieldBusinessType": "事業形態",
    "fieldEstablished": "設立年",
    "fieldEmployees": "従業員数",
    "fieldVerification": "検証ステータス",
    "fieldRiskScore": "リスクスコア",
    "fieldAuditStatus": "監査ステータス",
    "fieldInspectionHistory": "検品履歴",
    "fieldAccessTier": "公開レベル",
    "fieldPublished": "公開",
    "tier": "レベル",
    "tierHint": "public = 全員に公開。free = ログイン済みユーザー。paid = Founding Buyer のみ。",
    "riskHint": "スコアが高いほどリスクは低くなります。範囲は 0〜100 です。",
    "status": "ステータス",
    "yes": "はい",
    "no": "いいえ",
    "rfqsTitle": "見積依頼",
    "rfqsLead": "バイヤーからの見積依頼とそのステータス。",
    "rfqsEmpty": "見積依頼はまだありません",
    "statusNew": "新規",
    "statusReviewing": "対応中",
    "statusMatched": "マッチング済み",
    "statusClosed": "完了",
    "membersTitle": "メンバー",
    "membersLead": "アカウントと会員ステータス。",
    "membersEmpty": "メンバーはまだいません",
    "planFree": "無料",
    "planFounding": "Founding Buyer",
    "statusActive": "有効",
    "statusCanceled": "解約済み",
    "statusPastDue": "支払い期限超過",
    "statusExpired": "期限切れ",
    "notConfigured": "データがありません。データベースはまだ設定されていません。",
    "noData": "データなし",
}

AR = {
    "title": "لوحة الإدارة",
    "backToSite": "العودة إلى الموقع",
    "navLabel": "تنقل لوحة الإدارة",
    "navOverview": "نظرة عامة",
    "navSuppliers": "الموردون",
    "navRfqs": "طلبات عروض الأسعار",
    "navMembers": "الأعضاء",
    "overviewTitle": "نظرة عامة",
    "overviewLead": "نشاط المنصة في لمحة واحدة.",
    "statUsers": "المستخدمون",
    "statPaid": "الأعضاء المشتركون",
    "statSuppliers": "الموردون",
    "statNewRfqs": "طلبات جديدة (٧ أيام)",
    "statTotalRfqs": "إجمالي الطلبات",
    "recentRfqs": "أحدث الطلبات",
    "viewAll": "عرض الكل",
    "suppliersTitle": "الموردون",
    "suppliersLead": "عدّل سجلات الموردين وحدد من يمكنه رؤية كل ملف.",
    "suppliersEmpty": "لا يوجد موردون بعد",
    "suppliersEmptyHint": "شغّل سكربت الاستيراد أو أضف موردًا من هنا.",
    "colName": "الاسم",
    "colCountry": "الدولة",
    "colRisk": "درجة المخاطر",
    "colTier": "مستوى الوصول",
    "colPublished": "منشور",
    "colReference": "الرقم المرجعي",
    "colProduct": "المنتج",
    "colEmail": "البريد الإلكتروني",
    "colStatus": "الحالة",
    "colCreated": "تاريخ الإرسال",
    "colPlan": "الخطة",
    "colPeriodEnd": "نهاية الفترة",
    "edit": "تعديل",
    "backToList": "العودة إلى القائمة",
    "save": "حفظ التغييرات",
    "saving": "جارٍ الحفظ...",
    "saved": "تم الحفظ",
    "error": "حدث خطأ ما. يرجى المحاولة مرة أخرى.",
    "fieldLegalName": "الاسم القانوني",
    "fieldCity": "المدينة",
    "fieldIndustry": "القطاع",
    "fieldBusinessType": "نوع النشاط",
    "fieldEstablished": "سنة التأسيس",
    "fieldEmployees": "عدد الموظفين",
    "fieldVerification": "حالة التحقق",
    "fieldRiskScore": "درجة المخاطر",
    "fieldAuditStatus": "حالة التدقيق",
    "fieldInspectionHistory": "سجل الفحص",
    "fieldAccessTier": "مستوى الوصول",
    "fieldPublished": "منشور",
    "tier": "المستوى",
    "tierHint": "public = متاح للجميع. free = المستخدمون المسجلون. paid = حصري للأعضاء المؤسسين.",
    "riskHint": "الدرجة الأعلى تعني مخاطر أقل. النطاق من ٠ إلى ١٠٠.",
    "status": "الحالة",
    "yes": "نعم",
    "no": "لا",
    "rfqsTitle": "طلبات عروض الأسعار",
    "rfqsLead": "استفسارات المشترين وحالتها.",
    "rfqsEmpty": "لا توجد طلبات بعد",
    "statusNew": "جديدة",
    "statusReviewing": "قيد المراجعة",
    "statusMatched": "تمت المطابقة",
    "statusClosed": "مغلقة",
    "membersTitle": "الأعضاء",
    "membersLead": "الحسابات وحالة العضوية.",
    "membersEmpty": "لا يوجد أعضاء بعد",
    "planFree": "مجاني",
    "planFounding": "العضو المؤسس",
    "statusActive": "نشط",
    "statusCanceled": "ملغى",
    "statusPastDue": "متأخر السداد",
    "statusExpired": "منتهي",
    "notConfigured": "لا توجد بيانات: قاعدة البيانات غير مُعدة بعد.",
    "noData": "لا توجد بيانات",
}

ADMIN_BLOCKS = {
    "en": EN, "zh": ZH, "zh-TW": ZH_TW, "es": ES, "de": DE,
    "fr": FR, "pt": PT, "ja": JA, "ar": AR,
}

# membership 新增 2 个结账状态键
MEMBERSHIP_EXTRA = {
    "en": {"checkoutSubmitting": "Opening secure checkout...",
           "checkoutError": "Could not start checkout. Please try again or email us directly."},
    "zh": {"checkoutSubmitting": "正在前往安全结账页面…",
           "checkoutError": "无法启动结账，请重试或直接发邮件给我们。"},
    "zh-TW": {"checkoutSubmitting": "正在前往安全結帳頁面…",
              "checkoutError": "無法啟動結帳，請重試或直接來信給我們。"},
    "es": {"checkoutSubmitting": "Abriendo la pasarela de pago segura...",
           "checkoutError": "No se pudo iniciar el pago. Inténtelo de nuevo o escríbanos."},
    "de": {"checkoutSubmitting": "Sichere Kasse wird geöffnet...",
           "checkoutError": "Die Kasse konnte nicht gestartet werden. Bitte erneut versuchen oder uns direkt schreiben."},
    "fr": {"checkoutSubmitting": "Ouverture du paiement sécurisé...",
           "checkoutError": "Impossible de démarrer le paiement. Réessayez ou écrivez-nous directement."},
    "pt": {"checkoutSubmitting": "Abrindo o pagamento seguro...",
           "checkoutError": "Não foi possível iniciar o pagamento. Tente novamente ou envie-nos um e-mail."},
    "ja": {"checkoutSubmitting": "安全な決済画面を開いています...",
           "checkoutError": "決済を開始できませんでした。もう一度お試しいただくか、直接メールでご連絡ください。"},
    "ar": {"checkoutSubmitting": "جارٍ فتح صفحة الدفع الآمنة...",
           "checkoutError": "تعذّر بدء الدفع. يرجى المحاولة مرة أخرى أو مراسلتنا مباشرة."},
}


def main() -> int:
    os.makedirs(BACKUP_DIR, exist_ok=True)
    report = []

    for loc in LOCALES:
        path = os.path.join(DICT_DIR, f"{loc}.json")
        raw_before = io.open(path, "rb").read()
        crlf_before = raw_before.count(b"\r\n")

        # 备份
        shutil.copy2(path, os.path.join(BACKUP_DIR, f"{loc}.json"))

        # 读取（newline="" 保证不转换换行符）
        with io.open(path, "r", encoding="utf-8", newline="") as f:
            text = f.read()
        data = json.loads(text)

        changed = False

        # 1) admin 命名空间：缺失则整块写入
        if "admin" not in data:
            data["admin"] = ADMIN_BLOCKS[loc]
            changed = True
        else:
            # 已存在则只补缺键（不覆盖已有翻译）
            added = 0
            for k, v in ADMIN_BLOCKS[loc].items():
                if k not in data["admin"]:
                    data["admin"][k] = v
                    added += 1
            if added:
                changed = True
                report.append(f"  {loc}: admin 补 {added} 键")

        # 2) membership 两个结账键
        mem = data.get("membership")
        if isinstance(mem, dict):
            added_m = 0
            for k, v in MEMBERSHIP_EXTRA[loc].items():
                if k not in mem:
                    mem[k] = v
                    added_m += 1
            if added_m:
                changed = True
                report.append(f"  {loc}: membership 补 {added_m} 键")

        if not changed:
            report.append(f"  {loc}: 无变化，跳过")
            continue

        # 写回：json.dump 用 \n，统一替换成 \r\n
        out = json.dumps(data, ensure_ascii=False, indent=2)
        out_crlf = out.replace("\r\n", "\n").replace("\n", "\r\n") + "\r\n"
        with io.open(path, "w", encoding="utf-8", newline="") as f:
            f.write(out_crlf)

        raw_after = io.open(path, "rb").read()
        crlf_after = raw_after.count(b"\r\n")
        report.append(f"  {loc}: CRLF {crlf_before} -> {crlf_after}")

    print("[i18n] V2.1 admin/account 补齐完成")
    for line in report:
        print(line)
    return 0


if __name__ == "__main__":
    raise SystemExit(main())
