#!/usr/bin/env python3
# -*- coding: utf-8 -*-
"""
从本站 4 个内容源（lib/coverage.ts / guides.ts / fieldReports.ts / caseStudies.ts）抽取全部中文文案，
用 python opencc (s2twp) 繁化，生成「完整字符串映射 + 单字兜底表」供运行时深繁化 zh-TW 正文。

输出: lib/twData.generated.ts
用法: python scripts/gen-tw-mapping.py
（生成后勿手改；正文新增/变更中文时重跑本脚本）
"""
import json
import os
import re

import opencc

ROOT = os.path.dirname(os.path.dirname(os.path.abspath(__file__)))
SRC_FILES = [
    "lib/coverage.ts",
    "lib/guides.ts",
    "lib/fieldReports.ts",
    "lib/caseStudies.ts",
    # 2026-09-02 补：这两处中文也走 twText 兜底，纳入源表可让整串精确命中
    "lib/verification.ts",   # 证据类型标签（营业执照 / 审核报告 …）
    "lib/staticData.ts",     # 行业名「Electronics / 电子」
    # 页面里的硬编码中文（样例报告经营范围等）同样走 twText，
    # 纳入源表后整串精确命中，不再依赖单字兜底（「制造」词组级差异单字表覆盖不到）
    "app/[locale]/sample-report/page.tsx",
    # CS-02A：行业内容层（Master 页 Block A + 子主题正文）同样走 twText 兜底，
    # 纳入源表后可整串精确命中，避免「危害分析」「过敏原」等新词落回简体。
    "lib/industryContent.ts",
]
OUT = os.path.join(ROOT, "lib", "twData.generated.ts")

conv = opencc.OpenCC("s2twp")  # 与 zh-TW 字典同款转换


def extract_zh_strings(path: str) -> set:
    """抽取 TS 文件中所有含中文的字符串字面量（含键值中的 value）。"""
    text = open(path, encoding="utf-8").read()
    # 字符串字面量（双引号，含转义基本无）
    literals = re.findall(r'"((?:[^"\\]|\\.)*)"', text)
    out = set()
    for lit in literals:
        # 去掉常见转义
        lit = lit.replace('\\"', '"').replace("\\\\", "\\")
        if re.search(r"[\u4e00-\u9fff]", lit):
            out.add(lit)
    return out


def diff_chunks(a: str, b: str):
    """把两个等长串中「连续不同」的位置合并成块，返回 [(片段a, 片段b), ...]。

    「工厂生产管理 / 工廠生產管理」→ [("厂","廠"), ("产","產")]
    「信息 / 資訊」→ [("信息","資訊")]
    """
    chunks = []
    cur_a: list = []
    cur_b: list = []
    for x, y in zip(a, b):
        if x != y:
            cur_a.append(x)
            cur_b.append(y)
        elif cur_a:
            chunks.append(("".join(cur_a), "".join(cur_b)))
            cur_a, cur_b = [], []
    if cur_a:
        chunks.append(("".join(cur_a), "".join(cur_b)))
    return chunks


def main():
    all_zh: set = set()
    for f in SRC_FILES:
        all_zh |= extract_zh_strings(os.path.join(ROOT, f))

    # 1) 完整字符串映射（值含中文即收录；跳过含 {占位符} 的模板，保留给逐字兜底）
    str_map = {}
    for s in sorted(all_zh):
        tw = conv.convert(s)
        if tw != s:
            str_map[s] = tw

    # 2) 兜底表：把 s / tw 中「连续不同」的位置合并成块，逐块归类
    #
    # 坑（2026-09-02 修复，两处）：
    #   (a) 早先把等长串直接 zip 成单字表，遇到「词组级差异」就造出错表。
    #       opencc s2twp 里 窗口→視窗、集群→叢集、信息→資訊 都是整词替换，
    #       逐字 zip 会得出 窗→視 / 口→窗、集→叢 / 群→集、信→資 / 息→訊。
    #       结果：线上「進出口」被转成「進出窗」。
    #   (b) 第一版修复只取「首个差异～末个差异」一整段，把中间没变的字也吞进来，
    #       产出「厂生产→廠生產」这类伪词，真正的单字映射反而丢失。
    #       现在改成按连续差异位置切块：
    #         「工廠生產管理」→ 块「厂→廠」「产→產」（单字，进 char 表）
    #         「資訊」类词组差异 → 块「信息→資訊」（多字，进 phrase 表）
    #   - char 表再用 opencc 单字转换校验一次（口 单转仍为 口，故 口→窗 会被丢弃）
    #   - phrase 表同样校验，且只收纯中文 2–6 字的片段
    char_map = {}
    phrase_map = {}
    for s, tw in str_map.items():
        if len(s) != len(tw):
            continue
        for a, b in diff_chunks(s, tw):
            if len(a) == 1:
                if a not in char_map and conv.convert(a) == b:
                    char_map[a] = b
            elif re.fullmatch(r"[\u4e00-\u9fff]{2,4}", a):
                # 2–4 字：多半是 opencc 真正的词单位（信息→資訊、集群→叢集）
                if a not in phrase_map and conv.convert(a) == b:
                    phrase_map[a] = b
            else:
                # 更长的块是跨词片段（如「认证机构发证」），整块收录只会撑大产物、
                # 且换个上下文就可能误转。改为逐字校验后下沉到 char 表。
                for x, y in zip(a, b):
                    if x != y and x not in char_map and conv.convert(x) == y:
                        char_map[x] = y

    # 3) 词组表按长度降序，运行时做最长匹配（长的先替换，避免短词抢先命中）
    phrase_keys = sorted(phrase_map.keys(), key=len, reverse=True)

    # 3) 额外覆盖：直接对整库文本做一次 s2twp 得到的映射（保证「词级」差异如 软件→軟體 也能在整串未命中时用词表兜底）
    #    用最长匹配思路：把 s2twp 对完整文本产生的不同子串收集为词表过于复杂，
    #    此处仅保留单字表 + 全串表；未命中整串时按字表逐字转换，可保证繁化正确（含软体等词若在整串内已被精确覆盖）。

    payload = {
        "str": str_map,
        "phrase": {k: phrase_map[k] for k in phrase_keys},
        "char": char_map,
    }
    body = (
        "// GENERATED by scripts/gen-tw-mapping.py — 勿手改。\n"
        "// 内容源 zh 文案的 s2twp 繁化映射。\n"
        "//   str    完整字符串精确映射\n"
        "//   phrase 词组级差异（长度降序，运行时最长匹配）—— s2twp 的整词替换不能拆成单字\n"
        "//   char   单字兜底（已用 opencc 单字转换校验，不含词组级误拆）\n"
        "// 正文中文变更后重跑: python scripts/gen-tw-mapping.py\n"
        "export const TW_MAP: {\n"
        "  str: Record<string, string>;\n"
        "  phrase: Record<string, string>;\n"
        "  char: Record<string, string>;\n"
        "} = "
        + json.dumps(payload, ensure_ascii=False, indent=1)
        + ";\n"
    )
    with open(OUT, "w", encoding="utf-8") as f:
        f.write(body)
    size = os.path.getsize(OUT)
    print(
        f"str_map={len(str_map)} phrase_map={len(phrase_map)} char_map={len(char_map)} "
        f"-> {OUT} ({size / 1024:.1f} KB)"
    )


if __name__ == "__main__":
    main()
